name: ci
on:
  pull_request:
  push:
    branches: [ "master", "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            9.0.x
      - name: Restore
        run: dotnet restore ZEN/RichMove.SmartPay.sln
      - name: Build (Release, warn as error)
        run: dotnet build ZEN/RichMove.SmartPay.sln --configuration Release -warnaserror --no-restore
      - name: Format Check
        run: dotnet format ZEN/RichMove.SmartPay.sln --verify-no-changes
      - name: Test
        run: dotnet test ZEN/RichMove.SmartPay.sln --configuration Release --no-build --collect:"XPlat Code Coverage"
      - name: Upload coverage (artifact)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: |
            **/TestResults/*/coverage.cobertura.xml
            **/TestResults/*/coverage.xml

  # Optional: secret scan to prevent accidents
  secret_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: main
          head: HEAD